apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myshell
  name: myshell
spec:
  containers:
  - image: alpine
    name: myshell
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
