apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflect
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: reflect
  template:
    metadata:
      labels:
        app: reflect
    spec:
      containers:
      - image: gcr.io/istio-test-274718/reflect:latest
        name: reflect
        ports:
        - containerPort: 4000
